apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-os-centos8
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-os-centos8
    helm.sh/chart: gardener-extension-os-centos8
    app.kubernetes.io/instance: {{ .Release.Name }}
