// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "2433b54c07b5b13879d17545c6c7a2d1"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"4519213ea755c062667931666a639856": "1f8b08000000000000ff9c545b73ea36107ef7afd8999e39bc54be509219dcc9cb214d86930c939216022f19212d4641965c490ea1d4ffbd239b7009647a79b1a5d55ebeef5bad7e6052979c30ade6220b5646387c9e0b89360d361b107308bf69edac33b4005255018182ba450aad081d8beae0e61bb27916f28895d6e99c28742b6d964265dede0a000a34b9b05668655368c5979d8eb7a2629a0b95a530bbec04004c2b87caa5f057000030cb47316f77d7f44f7dd7ef7d7b99b52f723a6697fddb61c1da3762763b5af6b2ab2b8f1515af1136b085ed69e5a85068ae7f5174269143d81bf6cf90b06beb30e7db7fc4dee37868d1bc0a86218f9284e01bb2e746a7d0fffe37a97132904c4d8b497bc47bcb51673a1efcc66f6fd6fc3abe1b3e2de42419c493a7eff1c36337613ff55f27b92cefdb83d7991a2ee8f842b2fcd7ecfe317917a37bdf1ec59375d7efe3c95896d3a7efcbda3f9f16d3f5453c6b27f6834086aa0ce1cbf38ff0c5371bd22b086f7cd78fe5d96c9af3f081ba0554552bd86c8857776bddb387aa3a91631f7de4d724f160ea987f106b97a4d7d8a121b0e7420ec9944ab89accef4a387b701dea935d8e1392f5e98ee4bf027594f023a87dc96ba38bbeb26784e7f589477be419f61de667fad0b8ff4790dba02398e448bc8febaa0a02532a96f33420502a2724accb1c84b28e4a0964edb7a474425af8fab5de34434172aa68860608a19c138385868573854da388eb95929af2906bb64413329d4752a8f22d62a89cb65163270cc33aae497c585414ce0fb1859de77e4598147030b64283d58c3a5073bb452a7566b4a30ee1e50f5865e87e06aec14ac40212bf561810685e00e624708ab956c4a047fdd94bb87737681d356e0be9f3613b733f0fd360fd501d5cc901cdd177db0b725aedd4efa0f2df010000ffff35fc82bad9050000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("templates", "./templates")
		b.SetResolver("cloud-init-centos8.template", packr.Pointer{ForwardBox: gk, ForwardPath: "4519213ea755c062667931666a639856"})
	}()
	return nil
}()
